### ISSUE TITLE
Home Page - Links needed

### ISSUE THREAD

**Issue by KPDerosh** [baldr-io/baldr.io#1]
What links are needed for the home page nav bar.

Right now we have:
- Home which points to the Title section
- About which points to the about section
  ... Add others, maybe a social section pointing to a description of diaspora and a link to go to social.baldr.io

**Comment by Kelwing** [comment]
https://social.baldr.io - call it Social
https://status.baldr.io - call it Service Status
https://request.baldr.io - Call it Request Media
https://plex.baldr.io - call it Plex

**Comment by KPDerosh** [comment]
Should we have it link directly to the page or link to a section on the homepage about each of those things and then have a separate link there to actually link to the page.

**Comment by Kelwing** [comment]
Might be good to get @Gamer239 in on this discussion.  I think it honestly depends on the service.  Social and Plex should have their own section since they're primary services, but status and request should link directly to those pages since they augment out major services.

**Comment by Gamer239** [comment]
I agree with @Kelwing on having plex and social be their own sections. Just throwing out ideas here but it might be nice at some point to be able to give people a general status on their and/or all requests.

**Comment by KPDerosh** [comment]
I'll probably make a commit tonight to dev and pull to master. It with have all the links and two sections plex and social. I can look into doing a status bar or indication somewhere.
